# ============================================================
# Benchmark configuration for HTTP + Layered architecture
# Supports multi-service benchmarking (register, submit, evaluate, leaderboard)
# ============================================================

output_dir: ./bench_runs
timeout_seconds: 20

runs:
  # ----------------------------------------------------------
  - name: register
    url: http://localhost:8080/register
    json_body:
      username: "your_name"  # the name you input in the register step
      password: "your_password"  # the password you input in the register step
    concurrency_levels: [1, 2, 4, 8]
    requests_per_level: 50

  # ----------------------------------------------------------
  - name: submit
    url: http://localhost:8080/submit
    json_body:
      token: "" # the token of your account obtained by the login step
      challenge_id: "" # the token of the challenge obtained by the challenge create step
      payload:
        artifact: "demo_model_v1"
    concurrency_levels: [1, 2, 4, 8]
    requests_per_level: 50

  # ----------------------------------------------------------
  - name: evaluate
    url: http://localhost:8080/evaluate
    json_body:
      submission_id: "" # the token of submission obtained by the submission step
      challenge_id: "" # the token of the challenge obtained by the challenge create step
      # pred, float value
      pred: 0.7
    concurrency_levels: [1, 2, 4, 8]
    requests_per_level: 50

  # ----------------------------------------------------------
  - name: leaderboard
    url: http://localhost:8080/leaderboard?challenge_id=  # the token of the challenge obtained by the challenge create step
    json_body: {}
    concurrency_levels: [1, 2, 4, 8]
    requests_per_level: 50
