FROM python:3.8-buster
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --progress-bar off -r requirements.txt
COPY app.py /app/app.py
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
